// mac_llm_A.v
// Generated by LLM A (see mac_code_review.md for model version)
// 8-bit signed multiply-accumulate unit

module mac (
    input             clk,
    input             rst,
    input      [7:0]  a,
    input      [7:0]  b,
    output reg [31:0] out
);

    always @(posedge clk) begin
        if (rst)
            out <= 32'b0;
        else
            out <= out + (a * b);
    end

endmodule
