SIM = icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/conv2d_core.v
TOPLEVEL = conv2d_core
MODULE = test_conv2d_core
COMPILE_ARGS = -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
